apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: products-service-monitor
  namespace: monitoring
  labels:
    app: novalink
    component: products-service
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      component: products-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
