
#  ConfigMap — Variables de entorno compartidas

apiVersion: v1
kind: ConfigMap
metadata:
  name: novalink-config
  namespace: default
  labels:
    app: novalink
data:
  NODE_ENV: "production"
  DB_PORT: "5432"
  DB_USER: "novalink_user"
  JWT_SECRET_KEY: bm92YWxpbmstc2VjcmV0

  # Puertos de cada servicio
  USERS_PORT: "3001"
  PRODUCTS_PORT: "3002"
  ORDERS_PORT: "3003"
  NOTIFICATIONS_PORT: "3004"
  AUTH_PORT: "3005"

  # URLs de comunicación interna entre servicios 
  USERS_SERVICE_URL: "http://users-service:3001"
  PRODUCTS_SERVICE_URL: "http://products-service:3002"
  NOTIFICATIONS_SERVICE_URL: "http://notifications-service:3004"
  AUTH_SERVICE_URL: "http://auth-service:3005"
